### ISSUE TITLE
Rule engine

### ISSUE THREAD

**Issue by 1fexd** [LinkSheet/LinkSheet#494]
* [x] #136 (`fe/linksheet/experiment/engine/rule/UrlRewriteRuleTest.kt`)
* [x] #313 (`fe/linksheet/experiment/engine/rule/UrlRewriteRuleTest.kt`)
* [x] #407 (`fe/linksheet/experiment/engine/rule/UrlRewriteRuleTest.kt`)
* [x] #415 (`fe/linksheet/experiment/engine/rule/DefaultBrowserRuleTest.kt`)
* [x] #428 (`fe/linksheet/experiment/engine/rule/IntentAppOpenRuleTest.kt`)
* [x] #591 (`fe/linksheet/experiment/engine/rule/DefaultBrowserRuleTest.kt`)
